### ISSUE TITLE
How host this GIT on our own domain ?

### ISSUE THREAD

**Issue by jfg** [xdesro/personalsit.es#507]
Hello,
I would like to use your git for one of my website.
Is it possible and how ?
I don't want use netlify for this.
Thanks in advance.

**Comment by xdesro** [comment]
Sorry mate, no idea what you're asking. Good luck!

**Comment by jfg** [comment]
Hello,
How can i use (install) your git "personalsit.es" ?
Have you a setup guide or manual ?
Thanks

**Comment by binyamin** [comment]
> How can i use (install) your git "personalsit.es" ?

@jfg When you say "install" and "use", what do you mean? Those terms usually refer to programs such as mobile apps and desktop applications. Also, "git" is simply a command-line tool, so I assume you're referring to the code within the git _repository_ called "personalsit.es".

> Have you a setup guide or manual ?

This project uses NPM to generate some files, which Netlify automatically hosts as a website. When you said that you don't want to use Netlify for this, what would you like to use? For example, are you using GitHub's own hosting service, [GitHub Pages](https://pages.github.com)? Both Netlify and GitHub pages would be free for this use-case.

**Comment by binyamin** [comment]
@jfg I apologize if you already know the following information. I just want to make sure you receive an answer to your quesiton.

In order to run this website on your computer, you can follow the steps below.
1. I assume that you have already installed [Node.js](https://nodejs.dev/).
2. Copy the project onto your computer. You can use [Git](https://git-scm.com/) to clone this repository, or download the code as a zip file. [Here is a link to the zip file](https://github.com/xdesro/personalsit.es/archive/refs/heads/main.zip).
3. Navigate to the folder which contains the code. Install the dependencies by executing the command `npm install` within this folder.
4. Build the website by executing `npm run build`.
5. The `_site` folder now contains the website's files. Use them as you would any static website.
